<?php
/**
 * Hello World - Your First PHP Script
 * 
 * This is the traditional first program in any programming language.
 * It demonstrates the basic syntax of PHP.
 */

// Single line comment

/*
 * Multi-line comment
 * Can span multiple lines
 */

// Using echo to output text
echo "Hello, World!";
echo "<br>"; // HTML line break

// Using print (similar to echo)
print "Welcome to PHP Programming!";
echo "<br>";

// Echo with HTML
echo "<h1>PHP is Awesome!</h1>";
echo "<p>PHP stands for Hypertext Preprocessor</p>";

// Multiple parameters with echo
echo "You can ", "echo ", "multiple ", "strings!";
echo "<br>";

// PHP info (uncomment to see PHP configuration)
// phpinfo();

?>

<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
</head>
<body>
    <h2>PHP Inside HTML</h2>
    <?php
        echo "<p>This text is generated by PHP!</p>";
        echo "<p>Current date and time: " . date("Y-m-d H:i:s") . "</p>";
    ?>
</body>
</html>
